# Workflow to run RSpec tests
#  This uses a postgres db with the sv_SE locale.
#
#  @url Good overview of Github Actions: https://boringrails.com/articles/building-a-rails-ci-pipeline-with-github-actions/
#
#

name: rspec
on:
  workflow_dispatch:
  push:

env:
  RAILS_ENV: test
  RUBY_VERSION: 2.6.6
  GEMFILE_RUBY_VERSION: 2.7.2

  PGHOST: localhost
  PGUSER: postgres
  PGPASSWORD: password


jobs:

  linters-stylechecks:
    name: Linters and Stylechecks
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Setup Ruby and install gems
#        uses: ruby/setup-ruby@v1
#        with:
#          bundler-cache: true

      - name: Install Node version
        uses: actions/setup-node@v2.4.0
        with:
            node-version: '14.17.6'

#
#      - name: Find yarn cache location
#        id: yarn-cache
#        run: echo "::set-output name=dir::$(yarn cache dir)"
#
#      - name: JS package cache
#        uses: actions/cache@v1
#        with:
#          path: ${{ steps.yarn-cache.outputs.dir }}
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-

      - name: Install node packages with yarn
        run: |
          yarn install

      - uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          issueSummaryType: full
          reportIgnoredFiles: true


#      - name: css lint
#        run: |
#

#      - name: Run linters
#        run: |
#           bin/eslint
#          bin/rubocop --parallel
#          bin/stylelint
#          bin/prettier


#      - name: Run security checks
#        run: |
#          bin/bundler-audit --update
#          bin/brakeman -q -w2



#  tests:
#    name: RSpec tests
#    runs-on: ubuntu-18.04
#
#    services:
#      postgres:
#        # This image (from hub.docker.com) already has the sv_SE locale and collation set up.
#        # It is based on postgres:11
#        image: ashleyengelund/postgres-sv-se:postgres11-sv_se
#
#        env:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: password
#          POSTGRES_DB: shf_project_test
#
#        ports:
#          # Maps tcp port 5432 on service container to the host
#          - 5432:5432
#
#        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup Ruby and install gems
#        uses: ruby/setup-ruby@v1
#        with:
#          bundler-cache: true
#
#      - name: Install libpng12.so (required by IMGkit / wkhtmltoimage )
#        run: |
#          sudo wget http://se.archive.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
#          sudo dpkg -i libpng12-0_1.2.54-1ubuntu1_amd64.deb
#
#
#      - name: Connect to and set up the test database
#        run: |
#          bundle exec bin/rails db:create db:migrate
#          bundle exec bin/rails db:schema:dump
#          bundle exec bin/rails db:test:prepare
#
#
#      - name: Run tests that use wkhtmltoimage
#        run: bundle exec bin/rspec spec/controllers/users_controller_spec.rb

